// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:cf7013bc-b599-4436-8ff1-ac6827706b92",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_vEP9ZIrZn",
    "aws_user_pools_web_client_id": "37n37jtjl6fu00d1iuee8j3f1l",
    "oauth": {},
    "aws_content_delivery_bucket": "vue-contact-map-20200413075831-hostingbucket-proto",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://d3jsszy9vmlhyj.cloudfront.net",
    "aws_user_files_s3_bucket": "vue-contact-mapabc655a8e874453f89ce44bb2533e3d9map-proto",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};


export default awsmobile;
